<h1>Bibliotecas</h1>

In [1]:
import requests
import pandas as pd

from datetime import datetime
from pathlib import Path

<h1>Camara dos Deputados</h1>

<h2>Consulta - API</h2>

In [3]:
URL = 'https://dadosabertos.camara.leg.br/api/v2/proposicoes'

params = {
    "ano": 2026,
    "itens": 20,
    "ordem": "DESC",
    "ordenarPor": "id"
}

resposta = requests.get(URL, params=params)
print(resposta.status_code)

dados = resposta.json()

proposicoes = dados.get('dados', [])

df_raw = pd.DataFrame(proposicoes)

df_raw.head()

200

,id,uri,siglaTipo,codTipo,numero,ano,ementa,dataApresentacao
0,2623154,https://dadosabertos.camara.leg.br/api/v2/prop...,INC,133,701,2026,Indica ao Poder Executivo Federal a adoção de ...,2026-05-07T18:52
1,2623153,https://dadosabertos.camara.leg.br/api/v2/prop...,PL,139,2268,2026,Dispõe sobre a vedação da utilização de dispos...,2026-05-07T18:42
2,2623150,https://dadosabertos.camara.leg.br/api/v2/prop...,PL,139,2266,2026,"Altera a Lei nº 11.959, de 29 de junho de 2009...",2026-05-07T18:20
3,2623143,https://dadosabertos.camara.leg.br/api/v2/prop...,RIC,148,1229,2026,Requer informações ao Ministro de Estado das R...,2026-05-07T17:49
4,2623142,https://dadosabertos.camara.leg.br/api/v2/prop...,RIC,148,1228,2026,Requer informações ao Ministro de Estado da Sa...,2026-05-07T17:49

<h2>Extração</h2>

In [4]:
data_agora = datetime.now().strftime('%Y-%m-%d_%H-%M-%S')

caminho_saida = f'../dados/pipeline_verdadeiro_fontes_oficiais/raw/camara_proposicoes_raw_{data_agora}.csv'

df_raw.to_csv(caminho_saida, index=False, encoding='utf-8-sig')

print(f'Arquivo bruto salvo em: {caminho_saida}')

Arquivo bruto salvo em: ../dados/pipeline_verdadeiro_fontes_oficiais/raw/camara_proposicoes_raw_2026-05-08_00-54-05.csv

<h2>Curated</h2>

In [6]:
df_curated = df_raw.copy()

df_curated['texto_afirmacao'] = (

    'A proposição '
    + df_curated['siglaTipo'].astype(str)
    + ' '
    + df_curated['numero'].astype(str)
    + '/'
    + df_curated['ano'].astype(str)
    + 'foi registrada na Câmara Dos Deputados.'
)

df_curated['rotulo_binario'] = 'VERDADEIRO'
df_curated['fonte_verificada'] = 'CAMARA_DOS_DEPUTADOS'
df_curated['subtipo_falsidade'] = 'NA'
df_curated['tema'] = 'CONGRESSO'
df_curated['status_revisao'] = 'PENDENTE'

df_curated = df_curated[
    [
        'id',
        'texto_afirmacao',
        'rotulo_binario',
        'subtipo_falsidade',
        'tema',
        'fonte_verificada',
        'uri',
        'status_revisao'

    ]
].rename(columns={'uri':'url_fonte'})

df_curated.head()

,id,texto_afirmacao,rotulo_binario,subtipo_falsidade,tema,fonte_verificada,url_fonte,status_revisao
0,2623154,A proposição INC 701/2026foi registrada na Câm...,VERDADEIRO,NA,CONGRESSO,CAMARA_DOS_DEPUTADOS,https://dadosabertos.camara.leg.br/api/v2/prop...,PENDENTE
1,2623153,A proposição PL 2268/2026foi registrada na Câm...,VERDADEIRO,NA,CONGRESSO,CAMARA_DOS_DEPUTADOS,https://dadosabertos.camara.leg.br/api/v2/prop...,PENDENTE
2,2623150,A proposição PL 2266/2026foi registrada na Câm...,VERDADEIRO,NA,CONGRESSO,CAMARA_DOS_DEPUTADOS,https://dadosabertos.camara.leg.br/api/v2/prop...,PENDENTE
3,2623143,A proposição RIC 1229/2026foi registrada na Câ...,VERDADEIRO,NA,CONGRESSO,CAMARA_DOS_DEPUTADOS,https://dadosabertos.camara.leg.br/api/v2/prop...,PENDENTE
4,2623142,A proposição RIC 1228/2026foi registrada na Câ...,VERDADEIRO,NA,CONGRESSO,CAMARA_DOS_DEPUTADOS,https://dadosabertos.camara.leg.br/api/v2/prop...,PENDENTE